### ISSUE TITLE
Remonter tout ce qui est possible de la config du site à la config du thème

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme#11]
ex: 
paginate: 18
enableRobotsTXT: true

**Comment by sebousan** [comment]
@arnaudlevy  alors j'ai essayé, mais il semble que ce qu'on peut remonter est dans cette liste https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes

**Comment by arnaudlevy** [comment]
Cool, si c'est au max !
