### ISSUE TITLE
Mise à jour des thèmes

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny-hugo-theme#13]
- [x] Icons
- [x] Blocks
- [x] Custom
- [x] Purgecss theme vs template
- [ ] Étude du workflow des mises à jour
- [ ] Établir un schéma de fonctionnement
- [x] Rangement des styles (iso par block?)
- [x] Étudier une découpe par component (React / vue style)

**Comment by arnaudlevy** [comment]
Les blocs peuvent être dans toutes sortes de contextes, pas seulement les pages.
Peut-être dans les component ?

**Comment by sebousan** [comment]
à date, j'ai mis un block-partners.sass ds components.
Mais si on se retrouve avec des dizaines de blocks n'est-ce pas pertinent de le ranger ds un dossier ?
