### ISSUE TITLE
Il manque width et height dans le fichier media pour certaines images (ex: une image du block gallery)

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny-hugo-theme#25]
https://www.osuny.org/fonctionnalites/communication/sites-web/

Je vois des diffs : 
https://github.com/noesya/osuny-www/blob/main/data/media/47/478686a1-8033-4241-9c27-54b53793960c.yml
vs
https://github.com/noesya/osuny-www/blob/main/data/media/2f/2f00cbea-d53e-4636-8ffb-39ea3d4c2346.yml

Arnaud: 
_c’est une histoire de processing par rails avant l’export ou après l’export
si c’est processed avant, ça marche, on a la taille
sinon, il faudrait relancer un export
un truc qui réexporte après processing activestorage_

**Comment by arnaudlevy** [comment]
top !
