### ISSUE TITLE
Temps de compilation trop long : GetPageByUrl

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme#42]
## Identification

Le partial GetPageByUrl range sur toutes les pages du site à plusieurs endroits (menu, breadcrumb, partials de pages...)

Ce script ralenti grandement le temps de compilation du site :

```go
{{ $target := . }}
{{ $page := "" }}
{{ range site.Pages }}
  {{ $pageTarget := .RelPermalink }}
  {{ if eq $pageTarget $target }}
    {{ $page = . }}
  {{ end }}
{{ end }}
{{ return $page }}
```

## Piste : 

S'appuyer sur la fonction de site.GetPage tel que : 

```go 
{{ return site.GetPage (printf "/pages%s" .) }}
```

### Problème : 

Le script ci-dessus ne fonctionne que pour les pages de type "page", il faudrait pouvoir passer le "kind" car certaines pages ne sont pas de kind "page" (par exemple, l'index des "persons", des "posts"...)

**Comment by arnaudlevy** [comment]
C'est redevenu super bien, bravo !
