### ISSUE TITLE
Block video

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny-hugo-theme#50]
Ajouter un champ **titre de la video** car si on ne rentre pas de **titre** au block on n'a pas de title à mettre pour l'iframe, c'est non conforme.
ex: https://bordeauxmontaigne-iut.netlify.app/offre-de-formation/metiers-du-multimedia-et-de-l-internet/

**Comment by arnaudlevy** [comment]
Fait sur la branche refactor/blocks
