### ISSUE TITLE
Page plan du site

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny-hugo-theme#8]
On parle d'un plan du site lisible par un humain (pas d'un sitemap.xml)

ex: https://www.unilim.fr/plan-du-site/

Le faire générer automatiquement par Hugo ?

**Comment by sebousan** [comment]
@arnaudlevy  comment tu l'ajoutes à un menu ?

**Comment by arnaudlevy** [comment]
dans le legal, par défaut

**Comment by arnaudlevy** [comment]
est-ce qu'on l'écrit en dur dans le thème @pabois ?
Il me semble que oui.

**Comment by sebousan** [comment]
@pabois @arnaudlevy en dur ça va poser problème d'ordre ds ce menu legal
