### ISSUE TITLE
Flux RSS des actualités

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme#9]
https://gohugo.io/templates/rss/

**Comment by alexisben** [comment]
Le rss est déjà en place : https://bordeauxmontaigne-iut.netlify.app/actualites/index.xml 

Besoin de plus d'info sur ce point please

**Comment by pabois** [comment]
Bah voilà, on savait juste pas où il était^^
<https://noesya.coop/>

Pierre-André Boissinot

+33 6 64 33 86 11 <+33664338611>

*Noesya*
15 rue Hélène 75017 Paris
5 rue Joliot Curie 33150 Cenon
noesya.coop
<https://www.linkedin.com/company/noesyacoop>
<https://www.facebook.com/noesya.coop>

Envie de découvrir Noesya ? Prenez rendez-vous avec Arnaud en cliquant ici.
<https://calendly.com/arnaudlevy/decouvrir-noesya> Des questions sur les
communs numériques ?
C'est aussi avec Arnaud, et c'est par là !
<https://calendly.com/arnaudlevy/noesya-et-les-communs-numeriques> Des
questions sur les sites éco-conçus ? Prenez rendez-vous avec Sébastien.
<https://calendly.com/sebastienmoulene/noesya-et-les-sites-eco-concus> Des
questions sur les expériences interactives ? Prenez rendez-vous avec Alexis.
<https://calendly.com/alexisbenoit/noesya-et-les-experiences-interactives>


Le lun. 14 mars 2022 à 17:00, Alexis BENOIT ***@***.***> a
écrit :
